// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/task4_gpuyo/gold/task4a.gold"
package task4_gpuyo.gold;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import task4_gpuyo.gold.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class task4a {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet("q0","q1","q2","q3","q4","q5","q6","q7","q8","q9","q10","q11"));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('a','b'));
      $line=7;
      Object q=$fix("q0");
      $line=8;
      Object F=$fix(GCollections.asSet("q11"));
      $line=9;
      Object \u0394=$fix(new Object[]{new Object[]{"q0",'\u03BB',"q1"},new Object[]{"q0",'\u03BB',"q5"},new Object[]{"q1",'\u03BB',"q2"},new Object[]{"q1",'\u03BB',"q3"},new Object[]{"q2",'a',"q4"},new Object[]{"q3",'b',"q4"},new Object[]{"q4",'\u03BB',"q1"},new Object[]{"q4",'\u03BB',"q5"},new Object[]{"q5",'\u03BB',"q6"},new Object[]{"q6",'b',"q7"},new Object[]{"q7",'\u03BB',"q8"},new Object[]{"q8",'\u03BB',"q9"},new Object[]{"q8",'\u03BB',"q11"},new Object[]{"q9",'a',"q10"},new Object[]{"q10",'\u03BB',"q11"},new Object[]{"q10",'\u03BB',"q9"}});
      $line=43;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,\u0394}));
      $line=44;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task4a.class,"main",$line);
    }
  }
}
