// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/task6_gpuyo/gold/task6.gold"
package task6_gpuyo.gold;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import task6_gpuyo.gold.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class task6 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object letrasProposicionales=null;
  public static Object operadoresLogicos=null;
  public static Object parentesis=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=9;
      letrasProposicionales=$fix($opIntvlY('p','s'));
      $line=10;
      operadoresLogicos=$fix(GCollections.asSet('&','|','=','<','>','0'));
      $line=11;
      parentesis=$fix(GCollections.asSet('(',')'));
      $line=13;
      Object Q=$fix(GCollections.asSet("q0","q1","q2","q3","q4","q5","q6","q7","q8","q9","q10","q11","q12","q13","q14","q15","q16","q17","q18","q19","q20","q21","q22","q23","q24","q25","q26","q27","q28","q29","q30","q31","q32","q33","q34","q35","q36","q37","q38","q39","q40","q41","q42","q43","q44","q45","q46","err"));
      $line=18;
      Object \u03A3=$fix($opUnionY($opUnionY(letrasProposicionales,operadoresLogicos),parentesis));
      $line=19;
      Object q=$fix("q0");
      $line=20;
      Object F=$fix(GCollections.asSet("q15","q32"));
      $line=21;
      Object A=$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,new GMethod(task6.class,"\u03B4")}));
      $line=22;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task6.class,"main",$line);
    }
  }
  public static Object \u03B4(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=30;
      if (($opEqualY(state,"q0")&&$opMembrY(input,letrasProposicionales))) {
        $line=31;
        $result="q1";
        if (true) break $try;
      }
      else {
        $line=34;
        if (($opEqualY(state,"q1")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'&'))))) {
          $line=35;
          $result="q2";
          if (true) break $try;
        }
        else {
          $line=36;
          if (($opEqualY(state,"q2")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'&'))))) {
            $line=37;
            $result="q3";
            if (true) break $try;
          }
          else {
            $line=38;
            if (($opEqualY(state,"q3")&&$opMembrY(input,letrasProposicionales))) {
              $line=39;
              $result="q15";
              if (true) break $try;
            }
            else {
              $line=42;
              if (($opEqualY(state,"q1")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                $line=43;
                $result="q4";
                if (true) break $try;
              }
              else {
                $line=44;
                if (($opEqualY(state,"q4")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                  $line=45;
                  $result="q5";
                  if (true) break $try;
                }
                else {
                  $line=46;
                  if (($opEqualY(state,"q5")&&$opMembrY(input,letrasProposicionales))) {
                    $line=47;
                    $result="q15";
                    if (true) break $try;
                  }
                  else {
                    $line=50;
                    if (($opEqualY(state,"q4")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'>'))))) {
                      $line=51;
                      $result="q6";
                      if (true) break $try;
                    }
                    else {
                      $line=52;
                      if (($opEqualY(state,"q6")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'0'))))) {
                        $line=53;
                        $result="q1";
                        if (true) break $try;
                      }
                      else {
                        $line=56;
                        if (($opEqualY(state,"q1")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'='))))) {
                          $line=57;
                          $result="q7";
                          if (true) break $try;
                        }
                        else {
                          $line=58;
                          if (($opEqualY(state,"q7")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'>'))))) {
                            $line=59;
                            $result="q8";
                            if (true) break $try;
                          }
                          else {
                            $line=60;
                            if (($opEqualY(state,"q8")&&$opMembrY(input,letrasProposicionales))) {
                              $line=61;
                              $result="q15";
                              if (true) break $try;
                            }
                            else {
                              $line=64;
                              if (($opEqualY(state,"q7")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                                $line=65;
                                $result="q9";
                                if (true) break $try;
                              }
                              else {
                                $line=66;
                                if (($opEqualY(state,"q9")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,')'))))) {
                                  $line=67;
                                  $result="q10";
                                  if (true) break $try;
                                }
                                else {
                                  $line=68;
                                  if (($opEqualY(state,"q10")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'0'))))) {
                                    $line=69;
                                    $result="q11";
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=70;
                                    if (($opEqualY(state,"q11")&&$opMembrY(input,letrasProposicionales))) {
                                      $line=71;
                                      $result="q15";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=74;
                                      if (($opEqualY(state,"q1")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'<'))))) {
                                        $line=75;
                                        $result="q12";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=76;
                                        if (($opEqualY(state,"q12")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'='))))) {
                                          $line=77;
                                          $result="q13";
                                          if (true) break $try;
                                        }
                                        else {
                                          $line=78;
                                          if (($opEqualY(state,"q13")&&$opMembrY(input,letrasProposicionales))) {
                                            $line=79;
                                            $result="q15";
                                            if (true) break $try;
                                          }
                                          else {
                                            $line=82;
                                            if (($opEqualY(state,"q13")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'>'))))) {
                                              $line=83;
                                              $result="q14";
                                              if (true) break $try;
                                            }
                                            else {
                                              $line=84;
                                              if (($opEqualY(state,"q14")&&$opMembrY(input,letrasProposicionales))) {
                                                $line=85;
                                                $result="q15";
                                                if (true) break $try;
                                              }
                                              else {
                                                $line=91;
                                                if (($opEqualY(state,"q0")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,'('))))) {
                                                  $line=92;
                                                  $result="q16";
                                                  if (true) break $try;
                                                }
                                                else {
                                                  $line=93;
                                                  if (($opEqualY(state,"q16")&&$opMembrY(input,letrasProposicionales))) {
                                                    $line=94;
                                                    $result="q17";
                                                    if (true) break $try;
                                                  }
                                                  else {
                                                    $line=97;
                                                    if (($opEqualY(state,"q17")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'&'))))) {
                                                      $line=98;
                                                      $result="q18";
                                                      if (true) break $try;
                                                    }
                                                    else {
                                                      $line=99;
                                                      if (($opEqualY(state,"q18")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'&'))))) {
                                                        $line=100;
                                                        $result="q19";
                                                        if (true) break $try;
                                                      }
                                                      else {
                                                        $line=101;
                                                        if (($opEqualY(state,"q19")&&$opMembrY(input,letrasProposicionales))) {
                                                          $line=102;
                                                          $result="q31";
                                                          if (true) break $try;
                                                        }
                                                        else {
                                                          $line=105;
                                                          if (($opEqualY(state,"q17")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                                                            $line=106;
                                                            $result="q20";
                                                            if (true) break $try;
                                                          }
                                                          else {
                                                            $line=107;
                                                            if (($opEqualY(state,"q20")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                                                              $line=108;
                                                              $result="q21";
                                                              if (true) break $try;
                                                            }
                                                            else {
                                                              $line=109;
                                                              if (($opEqualY(state,"q21")&&$opMembrY(input,letrasProposicionales))) {
                                                                $line=110;
                                                                $result="q31";
                                                                if (true) break $try;
                                                              }
                                                              else {
                                                                $line=113;
                                                                if (($opEqualY(state,"q20")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'>'))))) {
                                                                  $line=114;
                                                                  $result="q22";
                                                                  if (true) break $try;
                                                                }
                                                                else {
                                                                  $line=115;
                                                                  if (($opEqualY(state,"q22")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'0'))))) {
                                                                    $line=116;
                                                                    $result="q17";
                                                                    if (true) break $try;
                                                                  }
                                                                  else {
                                                                    $line=119;
                                                                    if (($opEqualY(state,"q17")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'='))))) {
                                                                      $line=120;
                                                                      $result="q23";
                                                                      if (true) break $try;
                                                                    }
                                                                    else {
                                                                      $line=121;
                                                                      if (($opEqualY(state,"q23")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'>'))))) {
                                                                        $line=122;
                                                                        $result="q24";
                                                                        if (true) break $try;
                                                                      }
                                                                      else {
                                                                        $line=123;
                                                                        if (($opEqualY(state,"q24")&&$opMembrY(input,letrasProposicionales))) {
                                                                          $line=124;
                                                                          $result="q31";
                                                                          if (true) break $try;
                                                                        }
                                                                        else {
                                                                          $line=127;
                                                                          if (($opEqualY(state,"q23")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                                                                            $line=128;
                                                                            $result="q25";
                                                                            if (true) break $try;
                                                                          }
                                                                          else {
                                                                            $line=129;
                                                                            if (($opEqualY(state,"q25")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,')'))))) {
                                                                              $line=130;
                                                                              $result="q26";
                                                                              if (true) break $try;
                                                                            }
                                                                            else {
                                                                              $line=131;
                                                                              if (($opEqualY(state,"q26")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'0'))))) {
                                                                                $line=132;
                                                                                $result="q27";
                                                                                if (true) break $try;
                                                                              }
                                                                              else {
                                                                                $line=133;
                                                                                if (($opEqualY(state,"q27")&&$opMembrY(input,letrasProposicionales))) {
                                                                                  $line=134;
                                                                                  $result="q31";
                                                                                  if (true) break $try;
                                                                                }
                                                                                else {
                                                                                  $line=137;
                                                                                  if (($opEqualY(state,"q17")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'<'))))) {
                                                                                    $line=138;
                                                                                    $result="q28";
                                                                                    if (true) break $try;
                                                                                  }
                                                                                  else {
                                                                                    $line=139;
                                                                                    if (($opEqualY(state,"q28")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'='))))) {
                                                                                      $line=140;
                                                                                      $result="q29";
                                                                                      if (true) break $try;
                                                                                    }
                                                                                    else {
                                                                                      $line=141;
                                                                                      if (($opEqualY(state,"q29")&&$opMembrY(input,letrasProposicionales))) {
                                                                                        $line=142;
                                                                                        $result="q31";
                                                                                        if (true) break $try;
                                                                                      }
                                                                                      else {
                                                                                        $line=145;
                                                                                        if (($opEqualY(state,"q29")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'>'))))) {
                                                                                          $line=146;
                                                                                          $result="q30";
                                                                                          if (true) break $try;
                                                                                        }
                                                                                        else {
                                                                                          $line=147;
                                                                                          if (($opEqualY(state,"q30")&&$opMembrY(input,letrasProposicionales))) {
                                                                                            $line=148;
                                                                                            $result="q31";
                                                                                            if (true) break $try;
                                                                                          }
                                                                                          else {
                                                                                            $line=151;
                                                                                            if (($opEqualY(state,"q31")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,')'))))) {
                                                                                              $line=152;
                                                                                              $result="q32";
                                                                                              if (true) break $try;
                                                                                            }
                                                                                            else {
                                                                                              $line=159;
                                                                                              if (($opEqualY(state,"q32")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'&'))))) {
                                                                                                $line=160;
                                                                                                $result="q33";
                                                                                                if (true) break $try;
                                                                                              }
                                                                                              else {
                                                                                                $line=161;
                                                                                                if (($opEqualY(state,"q33")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'&'))))) {
                                                                                                  $line=162;
                                                                                                  $result="q34";
                                                                                                  if (true) break $try;
                                                                                                }
                                                                                                else {
                                                                                                  $line=163;
                                                                                                  if (($opEqualY(state,"q34")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,'('))))) {
                                                                                                    $line=164;
                                                                                                    $result="q16";
                                                                                                    if (true) break $try;
                                                                                                  }
                                                                                                  else {
                                                                                                    $line=167;
                                                                                                    if (($opEqualY(state,"q32")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                                                                                                      $line=168;
                                                                                                      $result="q35";
                                                                                                      if (true) break $try;
                                                                                                    }
                                                                                                    else {
                                                                                                      $line=169;
                                                                                                      if (($opEqualY(state,"q35")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                                                                                                        $line=170;
                                                                                                        $result="q36";
                                                                                                        if (true) break $try;
                                                                                                      }
                                                                                                      else {
                                                                                                        $line=171;
                                                                                                        if (($opEqualY(state,"q36")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,'('))))) {
                                                                                                          $line=172;
                                                                                                          $result="q16";
                                                                                                          if (true) break $try;
                                                                                                        }
                                                                                                        else {
                                                                                                          $line=175;
                                                                                                          if (($opEqualY(state,"q35")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'>'))))) {
                                                                                                            $line=176;
                                                                                                            $result="q37";
                                                                                                            if (true) break $try;
                                                                                                          }
                                                                                                          else {
                                                                                                            $line=177;
                                                                                                            if (($opEqualY(state,"q37")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'0'))))) {
                                                                                                              $line=178;
                                                                                                              $result="q38";
                                                                                                              if (true) break $try;
                                                                                                            }
                                                                                                            else {
                                                                                                              $line=181;
                                                                                                              if (($opEqualY(state,"q38")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'&'))))) {
                                                                                                                $line=182;
                                                                                                                $result="q33";
                                                                                                                if (true) break $try;
                                                                                                              }
                                                                                                              else {
                                                                                                                $line=183;
                                                                                                                if (($opEqualY(state,"q38")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                                                                                                                  $line=184;
                                                                                                                  $result="q35";
                                                                                                                  if (true) break $try;
                                                                                                                }
                                                                                                                else {
                                                                                                                  $line=185;
                                                                                                                  if (($opEqualY(state,"q38")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'='))))) {
                                                                                                                    $line=186;
                                                                                                                    $result="q39";
                                                                                                                    if (true) break $try;
                                                                                                                  }
                                                                                                                  else {
                                                                                                                    $line=187;
                                                                                                                    if (($opEqualY(state,"q38")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'<'))))) {
                                                                                                                      $line=188;
                                                                                                                      $result="q44";
                                                                                                                      if (true) break $try;
                                                                                                                    }
                                                                                                                    else {
                                                                                                                      $line=191;
                                                                                                                      if (($opEqualY(state,"q32")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'='))))) {
                                                                                                                        $line=192;
                                                                                                                        $result="q39";
                                                                                                                        if (true) break $try;
                                                                                                                      }
                                                                                                                      else {
                                                                                                                        $line=193;
                                                                                                                        if (($opEqualY(state,"q39")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'>'))))) {
                                                                                                                          $line=194;
                                                                                                                          $result="q40";
                                                                                                                          if (true) break $try;
                                                                                                                        }
                                                                                                                        else {
                                                                                                                          $line=195;
                                                                                                                          if (($opEqualY(state,"q40")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,'('))))) {
                                                                                                                            $line=196;
                                                                                                                            $result="q16";
                                                                                                                            if (true) break $try;
                                                                                                                          }
                                                                                                                          else {
                                                                                                                            $line=199;
                                                                                                                            if (($opEqualY(state,"q39")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'|'))))) {
                                                                                                                              $line=200;
                                                                                                                              $result="q41";
                                                                                                                              if (true) break $try;
                                                                                                                            }
                                                                                                                            else {
                                                                                                                              $line=201;
                                                                                                                              if (($opEqualY(state,"q41")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,')'))))) {
                                                                                                                                $line=202;
                                                                                                                                $result="q42";
                                                                                                                                if (true) break $try;
                                                                                                                              }
                                                                                                                              else {
                                                                                                                                $line=203;
                                                                                                                                if (($opEqualY(state,"q42")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'0'))))) {
                                                                                                                                  $line=204;
                                                                                                                                  $result="q43";
                                                                                                                                  if (true) break $try;
                                                                                                                                }
                                                                                                                                else {
                                                                                                                                  $line=205;
                                                                                                                                  if (($opEqualY(state,"q43")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,'('))))) {
                                                                                                                                    $line=206;
                                                                                                                                    $result="q16";
                                                                                                                                    if (true) break $try;
                                                                                                                                  }
                                                                                                                                  else {
                                                                                                                                    $line=209;
                                                                                                                                    if (($opEqualY(state,"q32")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'<'))))) {
                                                                                                                                      $line=210;
                                                                                                                                      $result="q44";
                                                                                                                                      if (true) break $try;
                                                                                                                                    }
                                                                                                                                    else {
                                                                                                                                      $line=211;
                                                                                                                                      if (($opEqualY(state,"q44")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'='))))) {
                                                                                                                                        $line=212;
                                                                                                                                        $result="q45";
                                                                                                                                        if (true) break $try;
                                                                                                                                      }
                                                                                                                                      else {
                                                                                                                                        $line=213;
                                                                                                                                        if (($opEqualY(state,"q45")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,'('))))) {
                                                                                                                                          $line=214;
                                                                                                                                          $result="q16";
                                                                                                                                          if (true) break $try;
                                                                                                                                        }
                                                                                                                                        else {
                                                                                                                                          $line=217;
                                                                                                                                          if (($opEqualY(state,"q45")&&$bool(($opMembrY(input,operadoresLogicos)&&$opEqualY(input,'>'))))) {
                                                                                                                                            $line=218;
                                                                                                                                            $result="q46";
                                                                                                                                            if (true) break $try;
                                                                                                                                          }
                                                                                                                                          else {
                                                                                                                                            $line=219;
                                                                                                                                            if (($opEqualY(state,"q46")&&$bool(($opMembrY(input,parentesis)&&$opEqualY(input,'('))))) {
                                                                                                                                              $line=220;
                                                                                                                                              $result="q16";
                                                                                                                                              if (true) break $try;
                                                                                                                                            }
                                                                                                                                            else {
                                                                                                                                              $line=224;
                                                                                                                                              $result="err";
                                                                                                                                              if (true) break $try;
                                                                                                                                            }
                                                                                                                                          }
                                                                                                                                        }
                                                                                                                                      }
                                                                                                                                    }
                                                                                                                                  }
                                                                                                                                }
                                                                                                                              }
                                                                                                                            }
                                                                                                                          }
                                                                                                                        }
                                                                                                                      }
                                                                                                                    }
                                                                                                                  }
                                                                                                                }
                                                                                                              }
                                                                                                            }
                                                                                                          }
                                                                                                        }
                                                                                                      }
                                                                                                    }
                                                                                                  }
                                                                                                }
                                                                                              }
                                                                                            }
                                                                                          }
                                                                                        }
                                                                                      }
                                                                                    }
                                                                                  }
                                                                                }
                                                                              }
                                                                            }
                                                                          }
                                                                        }
                                                                      }
                                                                    }
                                                                  }
                                                                }
                                                              }
                                                            }
                                                          }
                                                        }
                                                      }
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=226;
      $rethrow(new RuntimeException("The function \"\u03B4(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task6.class,"\u03B4",$line);
    }
    return $result;
  }
}
