// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/task2_gpuyo/gold/DFA2.gold"
package task2_gpuyo.gold;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import task2_gpuyo.gold.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class DFA2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet("q1","q2","q3","q4","q5","q6"));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('0','1','2'));
      $line=7;
      Object q=$fix("q1");
      $line=8;
      Object F=$fix(GCollections.asSet("q4"));
      $line=9;
      Object A=$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,new GMethod(DFA2.class,"\u03B4")}));
      $line=10;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,DFA2.class,"main",$line);
    }
  }
  public static Object \u03B4(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=15;
      if (($opEqualY(state,"q1")&&$opEqualY(input,'2'))) {
        $line=16;
        $result="q2";
        if (true) break $try;
      }
      else {
        $line=17;
        if (($opEqualY(state,"q1")&&$opEqualY(input,'1'))) {
          $line=18;
          $result="q4";
          if (true) break $try;
        }
        else {
          $line=19;
          if (($opEqualY(state,"q1")&&$opEqualY(input,'0'))) {
            $line=20;
            $result=state;
            if (true) break $try;
          }
          else {
            $line=23;
            if (($opEqualY(state,"q2")&&$opEqualY(input,'2'))) {
              $line=24;
              $result="q3";
              if (true) break $try;
            }
            else {
              $line=25;
              if (($opEqualY(state,"q2")&&$opEqualY(input,'1'))) {
                $line=26;
                $result="q5";
                if (true) break $try;
              }
              else {
                $line=27;
                if (($opEqualY(state,"q2")&&$opEqualY(input,'0'))) {
                  $line=28;
                  $result=state;
                  if (true) break $try;
                }
                else {
                  $line=31;
                  if (($opEqualY(state,"q3")&&$opEqualY(input,'2'))) {
                    $line=32;
                    $result="q1";
                    if (true) break $try;
                  }
                  else {
                    $line=33;
                    if (($opEqualY(state,"q3")&&$opEqualY(input,'1'))) {
                      $line=34;
                      $result="q6";
                      if (true) break $try;
                    }
                    else {
                      $line=35;
                      if (($opEqualY(state,"q3")&&$opEqualY(input,'0'))) {
                        $line=36;
                        $result=state;
                        if (true) break $try;
                      }
                      else {
                        $line=39;
                        if (($opEqualY(state,"q4")&&$opEqualY(input,'2'))) {
                          $line=40;
                          $result="q5";
                          if (true) break $try;
                        }
                        else {
                          $line=41;
                          if (($opEqualY(state,"q4")&&$opEqualY(input,'1'))) {
                            $line=42;
                            $result="q1";
                            if (true) break $try;
                          }
                          else {
                            $line=43;
                            if (($opEqualY(state,"q4")&&$opEqualY(input,'0'))) {
                              $line=44;
                              $result=state;
                              if (true) break $try;
                            }
                            else {
                              $line=47;
                              if (($opEqualY(state,"q5")&&$opEqualY(input,'2'))) {
                                $line=48;
                                $result="q6";
                                if (true) break $try;
                              }
                              else {
                                $line=49;
                                if (($opEqualY(state,"q5")&&$opEqualY(input,'1'))) {
                                  $line=50;
                                  $result="q2";
                                  if (true) break $try;
                                }
                                else {
                                  $line=51;
                                  if (($opEqualY(state,"q5")&&$opEqualY(input,'0'))) {
                                    $line=52;
                                    $result=state;
                                    if (true) break $try;
                                  }
                                  else {
                                    $line=55;
                                    if (($opEqualY(state,"q6")&&$opEqualY(input,'2'))) {
                                      $line=56;
                                      $result="q4";
                                      if (true) break $try;
                                    }
                                    else {
                                      $line=57;
                                      if (($opEqualY(state,"q6")&&$opEqualY(input,'1'))) {
                                        $line=58;
                                        $result="q3";
                                        if (true) break $try;
                                      }
                                      else {
                                        $line=59;
                                        if (($opEqualY(state,"q6")&&$opEqualY(input,'0'))) {
                                          $line=60;
                                          $result=state;
                                          if (true) break $try;
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=63;
      $rethrow(new RuntimeException("The function \"\u03B4(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,DFA2.class,"\u03B4",$line);
    }
    return $result;
  }
}
