// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/task5_gpuyo/gold/task5.gold"
package task5_gpuyo.gold;
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import task5_gpuyo.gold.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class task5 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=6;
      Object Q1=$fix(GCollections.asSet("A","B","C"));
      $line=7;
      Object \u03A31=$fix(GCollections.asSet('a','b'));
      $line=8;
      Object q1=$fix("A");
      $line=9;
      Object F1=$fix(GCollections.asSet("C"));
      $line=10;
      Object \u03941=$fix(new Object[]{new Object[]{"A",'a',"A"},new Object[]{"A",'a',"B"},new Object[]{"A",'b',"A"},new Object[]{"B",'a',"C"},new Object[]{"B",'b',"A"},new Object[]{"C",'\u03BB',"A"}});
      $line=27;
      Object Q2=$fix(GCollections.asSet("W","Z"));
      $line=28;
      Object \u03A32=$fix(GCollections.asSet('a','b'));
      $line=29;
      Object q2=$fix("W");
      $line=30;
      Object F2=$fix(GCollections.asSet("Z"));
      $line=31;
      Object \u03942=$fix(new Object[]{new Object[]{"W",'a',"W"},new Object[]{"W",'b',"W"},new Object[]{"W",'b',"Z"},new Object[]{"Z",'a',"Z"},new Object[]{"Z",'b',"Z"}});
      $line=44;
      Object A=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q1,\u03A31,q1,F1,\u03941}));
      $line=45;
      Object B=$fix($invokeConstructor(GNondeterministicAutomaton.class,new Object[]{Q2,\u03A32,q2,F2,\u03942}));
      $line=46;
      Object C=$fix(((gold.structures.automaton.GNondeterministicAutomaton)A).union($cast(gold.structures.automaton.IAutomaton.class,B)));
      $line=49;
      $invokeMethod(GAutomataFrame.class,"show",true,null,new Object[]{A,B,C});
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,task5.class,"main",$line);
    }
  }
}
